### ISSUE TITLE
(development branch) Clicking on map: no pin placed and no locations added

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/ghgvc#73]
note: this is only on the [development branch](http://github.com/ebimodeling/ghgvc/tree/development)

When I click on the map of the application running on the development branch, nothing happens and the website looks like this:
 
<img width="350" alt="screen shot 2016-02-16 at 4 38 02 pm" src="https://cloud.githubusercontent.com/assets/464871/13093590/c911818a-d4cb-11e5-8c48-a82a2e393835.png">

---

What I expect to appear is this:

<img width="350" alt="screen shot 2016-02-16 at 4 38 39 pm" src="https://cloud.githubusercontent.com/assets/464871/13093594/cd90200e-d4cb-11e5-9861-498d7449d5e6.png">

---

The development branch is currently running at www.ecosystemservicescalc.dev; for this site to load you need to add the line `128.174.127.81 www.ecosystemservicescalc.dev` to `/etc/hosts`

@potterzot is this something that you can fix, or should I ask @gsrohde to work on it in the rails application?

**Comment by potterzot** [comment]
Hi David - I'd say let me take a look at it first. I will have some time
tomorrow that I can investigate and get back to you.

---------------------
Nicholas Potter
http://potterzot.com

**Comment by potterzot** [comment]
Had to make a few housekeeping fixes. The ghgvc site is back to working locally. New commits have been pushed to the development branch of both ghgvc and ghgvcR. More information in the commit logs of each, but basically just grammatical fixes to function calls.

Note that if the rails server is run in development mode the location of the netcdf files needs to be changed in [workflows_controller.rb](https://github.com/ebimodeling/ghgvc/blob/development/app/controllers/workflows_controller.rb).

Leaving this issue open until we have a working version at http://www.ecosystemservicescalc.dev/.

**Comment by dlebauer** [comment]
@gsrohde can you tell me what would be required to update this on pecandev?

**Comment by gsrohde** [comment]
If you mean deploying the updated development branch code, it just means updating the ghgvc and ghgvcR working copies and restarting the Rails server—in other words, doing a `git pull` in both the `/usr/local/ghgvc-development/ghgvcR` directory and the `/usr/local/ghgvc-development/ghgvc` directory, and then doing a `touch tmp/restart.txt` in the `/usr/local/ghgvc-development/ghgvc` directory.  This copy runs in production mode (despite the name) so the remark above about changing `workflows_controller.rb` doesn't apply (unless, of course, we decide we really _do_ want to be running in development mode instead!).

**Comment by dlebauer** [comment]
I've run this on pecandev and still no points drop. 

@gsrohde could you please test this out?

**Comment by gsrohde** [comment]
@dlebauer OK, I'll take a look.  I'm going to play around with the code deployed at  www.ecosystemservicescalc.dev.  I'm assuming this is not going to interfere with anyone else's work.

**Comment by gsrohde** [comment]
@dlebauer Here's what I've found so far:

Beginning with commit version 68b770, the Rails action WorkflowsController#get_biome (which is called when you try to drop a pin) has been gutted and basically changed to be a wrapper around a system call to R that is supposed to do the real work.

The system call starts out like this:
```
cd #{@ghgvcR_instantiation_path} && ./inst/scripts/get_biome.R .......
```
Presumably the Ruby instance variable `@ghgvcR_instantiation_path` is supposed to be the path to the root of the ghgvcR working copy.  But it is actually undefined at this point.  (This would result in the `cd` switching directories to the home directory of the process owner, probably not what was intended.)

The instance variable `@ghgvcR_path` _is_ defined, however, so this may be what was intended.  In the production environment, it is set to `"#{Rails.root}/..ghgvcR"`, again, probably a typo and intended to be `"#{Rails.root}/../ghgvcR"`.

Even making these corrections, however, doesn't go very far towards fixing the problem.

First of all, the script `get_biome.R` doesn't exist in either repository.  My guess is that perhaps Nicholas forgot to check it in.

Second, following the portion of the system call shown above are several arguments to the R script, one of which is the textual rendition of a Ruby Hash variable called `@name_indexed_ecosystems`, which is basically the contents of the JSON file `public/data/final_ecosystems.json` converted to a Ruby   Hash.  On the command line, it gets printed out as
```
{"tropical peat forest"=>{"category"=>{"s000"=>"native"}, "T_A"=>{"s000"=>100}, "T_E"=>{"s000"=>50}, "r"=>{"s000"=>0}, "OM_ag"=>{"s000"=>444}, "OM_root"=>{"s000"=>108}, "OM_wood"=>{"s000"=>0}, "OM_litter"=>{"s000"=>0}, "OM_peat"=>{"s000"=>1388.889}, "OM_SOM"=>{"s000"=>88.96552}, "fc_ag_wood_litter"=>{"s000"=>0.5},
```
etcetera, which in no way can be parsed as a coherent UNIX command-line argument.  (In fact, the net result of this command is the creation of dozens of empty files with names like `{s000=` or `{category=`.)

Because of this last problem, I'm baffled as to how Nicholas could have gotten this working "locally", as he says, even if he does have the missing `get_biome.R` script.  It's possible his OS parses the command line differently, but this seems rather doubtful.

@dlebauer I don't think it makes sense for me to do any more work on this at this point without some further direction from you.

By the way, I should also mention there is a previous bug that prevents pins being dropped on North America.  I understand what is wrong but won't go into it here.

**Comment by dlebauer** [comment]
Nick - can you move this forward? Please set up call with Scott if
necessary

**Comment by potterzot** [comment]
get_biome.R is here:
https://github.com/ebimodeling/ghgvcR/tree/development/inst/scripts

It may be that your Ruby config doesn't point to the right directory that
contains the R scripts.

If that doesn't fix it, maybe we can have call tomorrow to work through it?
I could do 5pm Central, or for a short while at 2pm Central.

---------------------
Nicholas Potter
http://potterzot.com

**Comment by gsrohde** [comment]
@potterzot `get_biome.R` is indeed where it is supposed to be—I must have had the ghgvcR working copy on the wrong branch.  But all of the other problems I mention are still there.

I could do a call at 2pm or, for a short while at least, at 5.  Tomorrow is pretty much open too.  My number is (217) 244-0006, or if you prefer, I could call you.

**Comment by gsrohde** [comment]
@potterzot Short of a call, one thing to try is adding a debug line
```
logger.info("rcmd = #{rcmd}")
```
after line 225 of the file `workflows_controller.rb`, and then sending me the text of the R command that runs successfully on your local copy.  I can then try to see if I can get it running on my machine.

**Comment by dlebauer** [comment]
also, note that you should be able to find and execute to the correct (most recently installed) version of `get_biome.R` in R using:

```r
system.file("scripts/get_biome.R", package = "ghgvcr")
```

this can be executed within R on the command line as 

```r
system(system.file("scripts/get_biome.R", package = "ghgvcr"))
```

and can be executed from the bash shell as

```sh
 echo "system(system.file('scripts/get_biome.R', package = 'ghgvcr'))" | R --vanilla
```

**Comment by gsrohde** [comment]
This is the result of executing in R:
```
> system(system.file("scripts/get_biome.R", package = "ghgvcr"))
WARNING: ignoring environment value of R_HOME
Warning message:
package ‘ghgvcr’ was built under R version 3.1.0 
Error: Incorrect number of arguments.

        USAGE: 'get_biome.R <latitude> <longitude> <netcdf_dir> <named_ecosystems> <output_dir> [output_filename] [output_format] [write_data]'

        latitude:         The latitude to load data for.
        longitude:        The longitude to load data for.
        netcdf_dir:       Full path to the netcdf biome data.
        named_ecosystems: Full path to name-indexed ecosystems json file.
        output_dir:       Full path to write the biome data to.
        write_data:       OPTIONAL Boolean whether to write data to a file.
Execution halted
```
But I'm assuming you have to run the script _with arguments_.  That's what I want from @potterzot: A sample call _with arguments_ that actually runs successfully.

**Comment by potterzot** [comment]
The script call is in workflows_controller.rb. There is a line there that
calls get_biome.R with the associated arguments. I don't think I'm going to
get a chance to call today, and tomorrow I have to drive to seattle for an
ortho appt. I'll take a detailed look at it tonight and send you a working
example call, and then maybe we can set up a call for Wednesday.

---------------------
Nicholas Potter
http://potterzot.com

**Comment by potterzot** [comment]
Hi Scott,

Just double checked and the app runs on my laptop without problems, but
looking deeper, I found that it was working because there was a
"biome.json" file that it was reading as if the get_biome.R script had
successfully run.

I've pushed updates to both repos that work on my laptop, deleting the
biome.json file first (this gets deleted on the actual server right? I
assume it's tied to a specific user session or something but maybe we need
to implement that?). The plots don't work of course, but the console shows
that a js object gets loaded and that it has values.

There was also some confusion because the test.biome.R tests that I wrote
did not check the data writing process, only the returning of data, which,
from within R was working fine.

Sorry for all the confusion,
Nick

---------------------
Nicholas Potter
http://potterzot.com

**Comment by gsrohde** [comment]
@potterzot I'm not seeing anything new at https://github.com/ebimodeling/ghgvc or https://github.com/ebimodeling/ghgvcR.  Are you sure you pushed your updates and to the right place?

**Comment by potterzot** [comment]
@gsrohde you are entirely right. "git push origin master" is becoming a
little too habitual...

---------------------
Nicholas Potter
http://potterzot.com

**Comment by gsrohde** [comment]
@potterzot OK, I pulled the changes.  Now at least running the R code is attempted.  But I still get an error:
```
Error in missing(out_dir) : 'missing' can only be used for arguments
Calls: get_biome
Execution halted
```
(Then later, of course, the Rails code errors out because `tmp/run/biome.json` can't be found.)  I saw this error about "missing" earlier, when I tried to patch up the code myself.

**Comment by potterzot** [comment]
Did you also rebuild the ghgvcr package? That error is in the get_biome()
function but should have been fixed. I don't see a "out_dir" at all in any
of the source files at this point, and "missing(out_dir)" was changed to
"missing(output_dir)" to match the function parameter name, but it won't
pick that up unless the package is also reinstalled.

---------------------
Nicholas Potter
http://potterzot.com

**Comment by gsrohde** [comment]
@potterzot I'm not very familiar with R.  How do I rebuild the package?

**Comment by dlebauer** [comment]
@gsrohde

```
$ R CMD INSTALL /path/to/ghgvcR
```

Though you need to make sure that Ruby and you are installing into the the same R library (which it should by default if you don't have a custom library (e.g. `$R_LIBS_USER` environment var or `lib.Paths()` in `~/.Rprofile`.
 
I think at this point it would be useful for you and I to sit down. I'd like to learn how to run this thing on my OSX if its not too difficult. Then I can help you work through the R issues.

**Comment by dlebauer** [comment]
this is what I did

```
ssh pecandev
cd /usr/loca/ghgvc-development/ghgvcR
git checkout development # make sure on the dev branch
git pull
R CMD INSTALL .
tail -f /usr/local/ghgvc-development/ghgvc/log/production.log
```

then opened ecosystemservicescalc.dev and clicked and see this error in the log:

```
Error in get_ncdf(paste0(netcdf_dir, x$ncdir), x$ncfile, latitude, longitude,  : 
  file /usr/local/ghgvc-development/ghgvc/netcdf/saatchi.nc doesn't exist.
Calls: get_biome -> lapply -> FUN -> get_ncdf
Execution halted
 


r_outdir is /usr/local/ghgvc-development/ghgvc/tmp/run/


Completed 500 Internal Server Error in 2288ms

Errno::ENOENT (No such file or directory - /usr/local/ghgvc-development/ghgvc/tmp/run//biome.json):
  app/controllers/workflows_controller.rb:229:in `read'
  app/controllers/workflows_controller.rb:229:in `get_biomeR'
  app/controllers/workflows_controller.rb:251:in `get_biome'
```

So I think we are missing the saatchi.nc file, and therefore the biome.json file is not created.

**Comment by dlebauer** [comment]
Nick pointed out that the saatchi file was at /home/hmb/saatchi_final.nc. It is 7 GB so won't fit in the repository (we need to come up with a place to store these files to facilitate deployment). I've put the saatchi file in the right place

```
sudo cp /home/hmb/saatchi_final.nc /usr/local/ghgvc-development/ghgvc/netcdf/saatchi.nc
```

Now the button is placed ... but stay tuned for the next error. #74
